### ISSUE TITLE
How do I create a link?

### ISSUE THREAD

**Issue by dessalines** [asonix/activitypub#1]
I noticed there are methods like [set_audience_link](https://docs.rs/activitypub/0.1.4/activitypub/object/properties/struct.ObjectProperties.html#method.set_audience_link), but no way to actually create the link from a string? Some of the methods have set_string, but not all.

**Comment by asonix** [comment]
You're right that this should be a feature. I'll add this in tomorrow.

The reason it wasn't included originally was my misunderstanding of what it meant to be an Object or a Link when I first created this library. At any point when an Object or Link can be used, the ID of that Object or Link can be used in it's place.

If you want something that will work Right Now, you can do this:

```rust
struct MyLink(pub String);

impl activitypub::Link for MyLink {}
```

**Comment by asonix** [comment]
By the way, I hope your project goes well! I'm working on-and-off on [Aardwolf](https://github.com/Aardwolf-Social/aardwolf), myself. Let me know if you need anything else, or have an idea for some library we can share.

It might also be good to get in touch with the people working on [Plume](https://github.com/Plume-org/Plume) and [Rustodon](https://github.com/rustodon/rustodon). I've been keeping an eye on those projects for a while and Baptiste from Plume has had some ideas for i18n

**Comment by asonix** [comment]
I guess I should put this somewhere more visible, but I've moved many of my libraries related to this space into my Aardwolf organization on my Gitea instance: https://git.asonix.dog/Aardwolf. I'll soon have an actix-based jobs processor in here as well, but I'm working on the Oauth2 stuff before I get back to that.

**Comment by dessalines** [comment]
Sweet, thanks! And same for aardwolf, it looks great.

**Comment by asonix** [comment]
@dessalines the new version has been published

**Comment by dessalines** [comment]
I updated to `.15` but it still doesn't seem this was added, how do I do it? 

Also its possible to push to [multiple remotes](https://stackoverflow.com/a/3195446/1655478), I push all my repos to github, gitlab, and a self-hosted gitea for instance.

**Comment by asonix** [comment]
@dessalines https://docs.rs/activitypub/0.1.5/activitypub/object/properties/struct.ObjectProperties.html#method.set_audience_string
