### ISSUE TITLE
Crates.io package out of date

### ISSUE THREAD

**Issue by lamafab** [asonix/activitypub#2]
=> https://crates.io/crates/activitypub

The repository links to https://git.asonix.dog/Aardwolf/activitypub.git , which results in a `404`. Also, the latest version (`0.4.0`) does not offer you anything to work with.

![image](https://user-images.githubusercontent.com/42901763/145546603-e78e07d0-b5a0-45c9-add3-4a7907995ad2.png)

**Comment by asonix** [comment]
As it says on crates.io, the `activitypub` library is deprecated in favor of using the `activitystreams` library directly.

https://crates.io/crates/activitystreams
